DEMO_HOME=/home/demo
APP_HOME=${DEMO_HOME}/apps
BIN_DIR=${DEMO_HOME}/bin
DOWNLOAD_HOME=${DEMO_HOME}/Downloads
BOOKER_HOME=${DEMO_HOME}/booker
VAGRANT_HOME=/vagrant
MAVEN_HOME=${APP_HOME}/apache-maven-3.3.3

export DEMO_HOME APP_HOME BIN_DIR DOWNLOAD_HOME
export BOOKER_HOME VAGRANT_HOME MAVEN_HOME
